- apiId: hellow-demo-api
  displayName: Hello World Demo API
  path: /hello-world
  specPath: ./specs/openapi.yaml
  format: openapi
  serviceUrl: https://ileocecal-elnora-progambling.ngrok-free.dev/
  protocols:                           
    - https
  subscriptionRequired: false          
  productIds:                         
    - starter                        
    - unlimited                        
  gatewayNames:                       
    - managed                         
  tags:                               
    - demo
    - public
  apiDescription: Sample Hello World API for demonstration purposes
  apiType: http                       