- apiId: hellow-demo-api
  displayName: Hello World Demo API
  path: /hello-world
  specPath: ./specs/openapi.yaml
  format: openapi
  serviceUrl: https://ileocecal-elnora-progambling.ngrok-free.dev/
  protocols:                           
    - https
  subscriptionRequired: false          
  productIds:                         
    - starter                        
    - unlimited                        
  gatewayNames:                       
    - managed                         
  tags:                               
    - demo
    - public
  apiDescription: Sample Hello World API for demonstration purposes
  apiType: https
  policies:
    inbound:
      - type: validate-jwt
        header-name: Authorization
        failed-validation-httpcode: 401
        openid-config:
          url: https://dev-62exur2f3z3whnwh.us.auth0.com/.well-known/openid-configuration
